apiVersion: v1
kind: ConfigMap
metadata:
  name: opa-exemptions
  namespace: gatekeeper-system
  annotations:
    description: "Centralized exemption management for OPA policies - Strict Mode"
    managed-by: "platform-team"
    last-updated: "2025-01-23"
data:
  # Permanent exemptions - deployments that are permanently exempt from asset UUID requirements
  # Format: "namespace/deployment-name": "reason for exemption"
  # Note: In strict mode, permanent exemptions should be very limited
  permanent_exemptions: |
    {
      "monitoring/critical-prometheus": "Critical monitoring system - approved by security team"
    }
  
  # Time-based exemptions - deployments exempt until a specific date/time
  # Format: "namespace/deployment-name": "RFC3339 timestamp"
  # Note: In strict mode, time-based exemptions are for emergency situations only
  time_based_exemptions: |
    {
      "production/emergency-hotfix": "2025-01-25T10:00:00Z"
    }
  
  # Existing deployments - Not used in strict mode
  # Strict mode enforces policy on ALL deployments
  existing_deployments: |
    {}
  
  # Metadata about exemptions for auditing and tracking
  exemption_metadata: |
    {
      "monitoring/critical-prometheus": {
        "approved_by": "security-team",
        "approval_date": "2025-01-15",
        "review_date": "2025-04-15",
        "ticket": "SEC-9999",
        "justification": "Critical infrastructure component requiring special handling"
      },
      "production/emergency-hotfix": {
        "approved_by": "incident-commander",
        "approval_date": "2025-01-23",
        "reason": "Emergency production hotfix during incident INC-12345",
        "ticket": "INC-12345"
      }
    }
