apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: opa-strict-enforcement

resources:
  - constraint-template.yaml
  - constraint.yaml

labels:
  - pairs:
      scenario: strict-enforcement
      component: opa-policy

commonAnnotations:
  description: "OPA Gatekeeper configuration for strict asset UUID enforcement"
