apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: strict-enforcement-scenario

namespace: opa-strict-demo

resources:
  - namespace.yaml
  - base/
  - opa/

labels:
  - pairs:
      scenario: strict-enforcement
      managed-by: kustomize

commonAnnotations:
  description: "Complete strict enforcement scenario with OPA Gatekeeper"
  scenario.opa.example.com/type: "strict"
