apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: existing-deployment-overlay

resources:
  - existing-nginx.yaml

labels:
  - pairs:
      deployment-type: existing-legacy

commonAnnotations:
  description: "Overlay for existing deployments without assetUuid"
