apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AssetUuidRequired
metadata:
  name: asset-uuid-loose-warnings
  annotations:
    description: "ACME Payments Inc. FinOps - Loose Enforcement Warnings for Updates"
    organization: "ACME Payments Inc."
    policy-category: "finops-compliance"
    enforcement-level: "loose-warnings"
    rollout-strategy: "update-warnings"
spec:
  enforcementAction: warn  # Generate warnings for UPDATE operations
  parameters:
    enforcementMode: "loose-warnings"  # Special mode for warnings only
    exemptNamespaces:
      - "kube-system"
      - "kube-public"
      - "kube-node-lease"
      - "gatekeeper-system"
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces:
      - "opa-loose-demo"
    excludedNamespaces:
      - "kube-system"
      - "kube-public" 
      - "kube-node-lease"
      - "gatekeeper-system"
