apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nginx-strict-base

resources:
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml

labels:
  - pairs:
      scenario: strict-enforcement
      component: demo-app

commonAnnotations:
  description: "Base NGINX deployment for strict enforcement demo"
