apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: opa-loose-enforcement

resources:
  - constraint-template.yaml
  - constraint.yaml

labels:
  - pairs:
      scenario: loose-enforcement
      component: opa-policy

commonAnnotations:
  description: "OPA Gatekeeper configuration for loose asset UUID enforcement"
