apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacy-prometheus
  namespace: monitoring
  labels:
    app: legacy-prometheus
    # Note: Missing assetUuid label, but exempted via S3 configuration
  annotations:
    description: "Legacy monitoring system exempted via centralized S3 configuration"
    finops-status: "permanent-exemption"
    migration-planned: "Q2-2025"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacy-prometheus
  template:
    metadata:
      labels:
        app: legacy-prometheus
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: development
  labels:
    app: test-app
    # Note: Missing assetUuid label, but exempted via time-based S3 configuration
  annotations:
    description: "Test deployment with time-based exemption via centralized S3 configuration"
    finops-status: "time-based-exemption"
    exemption-expires: "2025-02-15T10:00:00Z"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
