apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-non-compliant-app
  labels:
    app: test-non-compliant-app
    # Note: Missing assetUuid label - this will trigger policy violation
  annotations:
    description: "Test deployment that violates asset UUID policy (missing assetUuid label)"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-non-compliant-app
  template:
    metadata:
      labels:
        app: test-non-compliant-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-non-compliant-app
  labels:
    app: test-non-compliant-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: test-non-compliant-app
